source 'https://rubygems.org'
gem 'jekyll', '3.1.2'
gem 'rouge', '1.10.1'
gem 'rb-fsevent', '0.9.7'
gem 'rb-inotify', '0.9.7'
gem 'celluloid-essentials', '>= 0'
gem 'celluloid-supervision', '>= 0'
gem 'celluloid-pool', '>= 0'
gem 'celluloid-fsm', '>= 0'
gem 'celluloid-extras', '>= 0'
gem 'hitimes', '>= 0'
